### ISSUE TITLE
Review notes

### ISSUE THREAD

**Issue by chrisvfritz** [BrandoBie/7_forms#1]
It looks like the Heroku app is showing the methods practice project. Can you update this showcase with an appropriate showcase? If you're not sure how, these steps should create a new Heroku app when run from your project directory:

``` bash
git remote rm heroku
heroku create
git push heroku master
heroku open
```

**Comment by BrandoBie** [comment]
Yea i forgot about the overlap. the new heroku is open and working.

**Comment by chrisvfritz** [comment]
Can you update the showcase with the link to the new Heroku app?

**Comment by BrandoBie** [comment]
I updated the showcase

**Comment by chrisvfritz** [comment]
:+1: Much better! Looking good.
